# Generate Contribution Snake
name: generate animation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']
    
  # Run automatically everyday
  schedule:
    - cron: "0 0 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Sets the GITHUB_TOKEN permissions
permissions:
  contents: write
  
jobs:
  # Single generate job
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates a snake game from a contributions graph and output svg animations
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark         
          
      # push the svg animations to a branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: output
          build_dir: dist
